# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = ""
  identifier = "home"
  url = "/"
  pre = "<i class='fa fa-home'></i>"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

[[main]]
  name = "Activities"  # Link title
  url = "/activities/"  # URL
  weight = 50  # Position
  identifier = "activities" # Identifier for sub menu

[[main]]
  name = "Teaching"  # link title
  url = "/activities/teaching/"  # url
  weight = 51  # position in navigation
  parent = "activities" # link to top navigation item

[[main]]
  name = "Research"  # A link title for your page.
  url = "/activities/research/"  # The URL of your page.
  weight = 52  # The position of your page in the menu.
  parent = "activities"

[[main]]
  name = "Innovation"  # A link title for your page.
  url = "/activities/innovation/"  # The URL of your page.
  weight = 53  # The position of your page in the menu.
  parent = "activities"

[[main]]
  name = "Executive education"  # A link title for your page.
  url = "/activities/executive-education/"  # The URL of your page.
  weight = 54  # The position of your page in the menu.
  parent = "activities"

[[main]]
  name = "Community and Dissemination"  # A link title for your page.
  url = "/activities/community-dissemination/"  # The URL of your page.
  weight = 55  # The position of your page in the menu.
  parent = "activities"
  
[[main]]
  name = "About"
  url = "/about/"
  weight = 60
  identifier = "about"

[[main]]
  name = "Ambition"
  url = "/about/ambition/"
  weight = 61
  parent = "about"

[[main]]
  name = "Approach"
  url = "/about/approach/"
  weight = 62
  parent = "about"

[[main]]
  name = "Team"
  url = "/about/team/"
  weight = 63
  parent = "about"

[[main]]
  name = "Partners"
  url = "/about/partners/"
  weight = 64
  parent = "about"

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
